---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spug
  name: spug-nfs-spug
  labels: {}
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spug
  name: spug-nfs-repos
  labels: {}
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spug
  namespace: spug
  labels:
    app: spug
  annotations:
    deployment.kubernetes.io/revision: '7'
    kubesphere.io/creator: admin
spec:
  replicas: 6
  selector:
    matchLabels:
      app: spug
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spug
      annotations:
        app: spug
        kubesphere.io/creator: admin
        kubesphere.io/imagepullsecrets: '{"spug":"aliyun-dockerhub"}'
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: spug
          persistentVolumeClaim:
            claimName: spug-nfs-spug
        - name: repos
          persistentVolumeClaim:
            claimName: spug-nfs-repos
      containers:
        - name: spug
          image: 'registry.cn-hangzhou.aliyuncs.com/gasly/spug:SNAPSHOT-BUILD_NUMBER'
          ports:
            - name: http-0
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: spug
              mountPath: /data/spug
            - name: repos
              mountPath: /data/repos
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: aliyun-dockerhub
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
